const fs = require('fs');
const path = 'c:/Users/Dullio Macedo/OneDrive/Documents/Arquivos Antigravity/workspaces/giborba/website-gi-borba/gi-borba/index.html';

function faqItem(id, question, snippet, body, open) {
  return `
      <div class="faq-item${open ? ' faq-item--open' : ''}" id="${id}">
        <button class="faq-question" aria-expanded="${open ? 'true' : 'false'}" aria-controls="ans-${id}">${question}<span class="faq-question__icon" aria-hidden="true"><svg viewBox="0 0 24 24"><polyline points="6,9 12,15 18,9" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg></span></button>
        <div class="faq-answer" id="ans-${id}" role="region"><div class="faq-answer__inner"><span class="faq-answer__snippet">${snippet}</span><p class="faq-answer__body">${body}</p></div></div>
      </div>`;
}

function cat(num, title, items) {
  return `
    <div class="faq__category" aria-labelledby="faq-cat${num}">
      <h3 id="faq-cat${num}" class="faq__category-heading"><span class="faq__category-num" aria-hidden="true">${num}</span>${title}</h3>
      ${items}
    </div>`;
}

const faqHtml = `
<!-- FAQ -->
<section id="faq" class="section" aria-labelledby="faq-heading">
  <div class="container">
    <span class="section-label">Perguntas frequentes</span>
    <h2 id="faq-heading" class="section-heading">Gi responde</h2>
` +
cat(1, 'O Que É Yoga: Conceito e Fundamentos',
  faqItem('o-que-e-yoga','O que é yoga e para que serve?','Yoga é uma prática que combina posturas físicas, respiração consciente e atenção ao corpo. Serve para reduzir ansiedade, melhorar o sono, aliviar dores crônicas e recuperar a sensação de equilíbrio. Não é religião, não exige flexibilidade e não depende de nenhuma crença espiritual — funciona por biologia, não por misticismo.','Quando o sistema nervoso vive em estado crônico de alerta, o corpo acumula tensão que nenhuma atividade convencional consegue desfazer por completo. O yoga atua diretamente nesse sistema: através da respiração controlada e do movimento consciente, ativa o sistema nervoso parassimpático e interrompe o ciclo de cortisol elevado. Uma hora de yoga bem conduzida reduz a frequência cardíaca, diminui a pressão arterial, melhora a qualidade do sono naquela noite e alivia tensões musculares. Com a prática regular, esses efeitos se tornam cumulativos e estruturais.',true)+
  faqItem('yoga-ioga-grafia','Yoga e ioga: qual a forma correta de escrever?','As duas formas estão corretas em português brasileiro. "Ioga" é a grafia aportuguesada, adotada pelo Acordo Ortográfico de 1990. "Yoga" é a grafia original em sânscrito e a mais usada no Brasil em contexto cotidiano, profissional e nas buscas online. Ambas se referem à mesma prática.','Na prática, "yoga" domina absolutamente o uso real — nas buscas do Google, nas redes sociais, nos estúdios e nas conversas. "Ioga" aparece principalmente em textos formais ou jornalísticos que seguem estritamente o acordo ortográfico. Para fins de comunicação e SEO, "yoga" é o termo a priorizar.',false)+
  faqItem('yoga-significado','O que significa yoga em sânscrito?','"Yoga" vem da raiz sânscrita "yuj", que significa unir, conectar, integrar. A tradução mais precisa é "união" — a integração entre corpo, mente e respiração. Não é uma tradução poética: é uma descrição literal do que a prática faz fisiologicamente — criar coerência entre sistemas que habitualmente operam em conflito.','No contexto original, a "união" se referia à integração do indivíduo com o todo — um conceito filosófico profundo. Na prática contemporânea e laica, a mesma palavra descreve algo igualmente real: o estado de coerência interna que emerge quando corpo, respiração e atenção trabalham juntos em vez de em direções opostas.',false)+
  faqItem('yoga-origem','Onde surgiu o yoga e qual é sua origem?','O yoga surgiu na Índia há mais de 5.000 anos, desenvolvido dentro das tradições filosóficas do subcontinente indiano. Os primeiros registros escritos aparecem nos Vedas, textos sagrados indianos. A sistematização da prática como a conhecemos hoje foi compilada por Patañjali nos Yoga Sutras, por volta do ano 400 d.C.','O yoga chegou ao Ocidente no final do século XIX e início do XX, e ao Brasil de forma mais estruturada na segunda metade do século XX. No Brasil, destaca-se a tradição SwáSthya, desenvolvida pelo mestre Caio Miranda, com raiz genuinamente brasileira. Hoje, o yoga praticado no mundo ocidental é majoritariamente focado nos aspectos físicos e de regulação mental.',false)+
  faqItem('yoga-exercicio-fisico','Yoga é exercício físico ou prática espiritual?','Yoga é as duas coisas — e também pode ser nenhuma das duas. É uma prática que tem dimensão física (posturas, força, flexibilidade), dimensão mental (atenção, regulação do sistema nervoso) e, para quem escolher, dimensão filosófica ou espiritual. Cada praticante decide até onde quer ir. Os benefícios físicos e mentais estão disponíveis independentemente de qualquer escolha espiritual.','Classificar yoga como "só exercício físico" seria reduzir. Classificar como "só prática espiritual" seria excluir. A realidade é que yoga é uma tecnologia de integração — entre corpo e mente, entre esforço e descanso, entre o que você faz e o que você sente. Essa integração produz benefícios fisiológicos documentados, independentemente da cosmologia de quem pratica.',false)+
  faqItem('yoga-oms','Yoga conta como exercício físico segundo a OMS?','Sim. A OMS classifica yoga como atividade física moderada a vigorosa, dependendo da modalidade. Modalidades ativas como Vinyasa e Yoga HIIT atingem frequência cardíaca comparável a uma caminhada acelerada ou corrida leve. Modalidades mais suaves como Hatha e Restaurativo promovem benefícios musculares, de flexibilidade e de regulação do sistema nervoso sem carga cardiovascular intensa.','Para as recomendações globais de atividade física — 150 minutos de atividade moderada por semana — o yoga ao vivo com um professor qualificado conta integralmente. Isso é especialmente relevante para quem tem restrições articulares ou cardiovasculares que limitam outras formas de exercício.',false)
)+
cat(2, 'Como Começar: Primeiros Passos no Yoga',
  faqItem('yoga-sem-flexibilidade','Posso fazer yoga sem ser flexível?','Sim. Flexibilidade não é pré-requisito para o yoga — é consequência. Quem começa sem flexibilidade tem exatamente o yoga que precisa: adaptado ao corpo que tem hoje. Forçar além do que o corpo oferece não acelera o processo — machuca. Com prática regular, o tecido conjuntivo cede gradualmente, e a abertura acontece de dentro para fora.','A imagem do yoga nas redes sociais filtra, por natureza, o que é visualmente impressionante. Esse filtro cria a falsa ideia de que yoga é para quem já é flexível — quando na realidade é o oposto. Anatomicamente: a rigidez corporal raramente é só muscular. É também uma resposta do sistema nervoso. O yoga trabalha essa camada. Após algumas semanas de prática consistente, a maioria dos iniciantes percebe mudanças não porque o músculo cresceu, mas porque o sistema nervoso aprendeu que é seguro ceder.',true)+
  faqItem('yoga-em-casa-iniciantes','Como fazer yoga em casa para iniciantes?','Para começar yoga em casa: escolha um espaço com área suficiente para deitar de braços abertos, providencie um tapete antiderrapante, vista roupa confortável e conecte-se a uma aula com professor ao vivo. Evitar começar sozinha com vídeos gravados — sem correção de postura em tempo real, é fácil criar hábitos errados que causam dor em vez de alívio.','O erro mais comum de quem começa em casa é substituir o professor por uma biblioteca de vídeos. Vídeos gravados são úteis para complementar a prática, mas não veem você. Um professor ao vivo vê o alinhamento, percebe a compensação que você faz sem saber, e adapta a aula ao que seu corpo está fazendo naquele dia. Para as primeiras semanas: comece com aulas de 45 a 60 minutos duas ou três vezes por semana.',false)+
  faqItem('frequencia-yoga','Quantas vezes por semana devo fazer yoga?','Para resultados perceptíveis no sono, na ansiedade e na flexibilidade: duas a três vezes por semana é suficiente para começar. Para quem quer progressão mais rápida em força e mobilidade: quatro vezes ou mais. Praticar uma vez por semana mantém o contato com a prática, mas raramente produz mudanças estruturais no sistema nervoso.','A frequência ideal depende do objetivo. Para regulação do sistema nervoso e melhora do sono, a consistência importa mais do que a intensidade: duas sessões por semana durante dois meses superam em muito uma sessão por dia durante duas semanas. O corpo responde a padrões repetidos, não a esforços isolados.',false)+
  faqItem('yoga-todos-os-dias','Posso fazer yoga todos os dias?','Sim, é possível e benéfico praticar yoga diariamente — com uma condição: variar a intensidade. Dias de prática ativa devem alternar com dias de prática regenerativa. O erro é manter a mesma intensidade todos os dias, sem deixar o sistema nervoso e o tecido conjuntivo recuperarem.','O corpo humano adulto saudável se adapta bem à prática diária de yoga quando a prática é inteligentemente variada. Culturas que praticam yoga diariamente há gerações sabem disso: a manhã começa com uma prática suave de ativação; sessões mais intensas ficam para momentos específicos da semana. Essa variação não é preguiça — é periodização.',false)+
  faqItem('horario-yoga','Qual o melhor horário para fazer yoga?','Não existe um horário universalmente melhor — existe o horário que você consegue manter. Yoga pela manhã tende a energizar e estabelecer o tom mental do dia. Yoga à tarde ou à noite tende a desacelerar, reduzir a tensão acumulada e preparar o sistema nervoso para o sono. O pior horário é aquele que você nunca consegue respeitar.','Para quem tem dificuldade de dormir: uma aula de Hatha, Restaurativo ou Yoga Nidra entre 18h e 21h produz redução mensurável nos níveis de cortisol antes de dormir. Para quem quer energia e foco pela manhã: uma prática de 30 a 45 minutos antes do café cria um estado de alerta calmo que a cafeína sozinha não consegue replicar.',false)+
  faqItem('tempo-resultado-yoga','Quanto tempo de yoga por dia é necessário para sentir resultado?','Sessões de 45 a 60 minutos, duas a três vezes por semana, produzem resultados perceptíveis em duas a quatro semanas — especialmente em qualidade do sono, nível de ansiedade e mobilidade. Os primeiros resultados costumam aparecer antes de qualquer mudança visível no corpo: a cabeça muda antes dos músculos.','A ordem de aparecimento dos resultados é previsível: primeiro vem a melhora do sono (semanas 1 a 2). Depois a redução da ansiedade e do nível basal de tensão muscular (semanas 2 a 6). Depois as mudanças de flexibilidade e força (semanas 4 a 12). As mudanças de composição corporal são as últimas a aparecer.',false)+
  faqItem('material-yoga','O que preciso para começar a fazer yoga em casa?','Para começar: um tapete de yoga antiderrapante (6mm de espessura é suficiente), roupa confortável que permita movimento, um espaço de aproximadamente 2m x 1m e conexão à internet para aulas ao vivo. Blocos de yoga e cintos são úteis mas não obrigatórios no início — uma professora experiente adapta as posturas ao que você tem em casa.','O investimento inicial é mínimo. O tapete é o único equipamento verdadeiramente necessário, e um bom tapete de entrada custa entre R$80 e R$150. O que determina o resultado não é o equipamento — é a consistência da prática e a qualidade do acompanhamento.',false)
)+
cat(3, 'Yoga e Saúde: Evidências e Benefícios',
  faqItem('yoga-ansiedade','Yoga ajuda na ansiedade? Existe prova científica?','Sim, e a evidência é robusta. Estudos publicados em periódicos como o Journal of Clinical Psychiatry documentam redução significativa de sintomas de ansiedade em praticantes regulares de yoga. O mecanismo é fisiológico: técnicas de respiração ativam o nervo vago, reduzem o cortisol e desaceleram o sistema nervoso autônomo — efeitos mensuráveis em uma única sessão.','A diferença entre "fazer yoga uma vez" e "praticar yoga regularmente" é a diferença entre apagar um incêndio e instalar um sistema de prevenção. Uma sessão reduz a ansiedade momentaneamente. A prática consistente recalibra o ponto de equilíbrio do sistema nervoso. Para quem vive em estado crônico de alerta, o yoga oferece uma via de saída que não depende de força de vontade: você não precisa "querer relaxar". O sistema nervoso responde ao estímulo da respiração independentemente da intenção consciente.',true)+
  faqItem('yoga-insonia','Yoga melhora a insônia?','Sim. O yoga melhora o sono por dois caminhos complementares: regula os picos de cortisol ao longo do dia e, nas horas antes de dormir, ativa o sistema nervoso parassimpático. Um estudo publicado na Revista Brasileira de Medicina de Família e Comunidade documentou melhora significativa da insônia em mulheres na pós-menopausa com prática regular de yoga. A maioria das praticantes relata melhora perceptível nas primeiras duas semanas.','A insônia mais comum não é a incapacidade de adormecer — é a incapacidade de desligar. A mente continua processando o dia depois que o corpo deitou. Isso acontece porque o sistema nervoso nunca recebeu o sinal claro de que o dia terminou. O yoga oferece esse sinal: posturas suaves, respiração longa e o descanso final da aula preparam o sistema nervoso para o descanso de forma que a maioria das outras práticas não consegue.',false)+
  faqItem('yoga-coluna','Yoga é bom para a coluna?','Sim — quando praticado com orientação adequada. O yoga atua na dor lombar crônica por múltiplos caminhos: fortalece a musculatura profunda do core, melhora a mobilidade dos quadris e isquiotibiais e corrige padrões posturais inadequados. Atenção: fazer yoga sem professor para condições de coluna pode piorar em vez de melhorar — a presença de quem vê e adapta é fundamental.','A dor lombar crônica raramente tem uma causa única. É quase sempre uma combinação de músculos enfraquecidos que sobrecarregam as vértebras, tecidos encurtados que distorcem o alinhamento e padrões de movimento inadequados aprendidos ao longo de anos. O yoga endereça todas essas camadas simultaneamente.',false)+
  faqItem('yoga-cerebro','Yoga pode adiar o envelhecimento do cérebro?','Evidências preliminares sugerem que sim. Estudos de neuroimagem identificaram maior volume de matéria cinzenta em regiões associadas à memória e ao processamento emocional em praticantes de longa data de yoga e meditação, comparados a não praticantes da mesma faixa etária. A prática regular parece ter efeito neuroprotetor.','O mecanismo proposto envolve a redução crônica do cortisol — que em níveis elevados é neurotóxico para o hipocampo, região crítica para a memória. Ao reduzir o estado de alerta crônico, o yoga protege estruturas cerebrais que o estresse degrada ao longo do tempo.',false)+
  faqItem('yoga-corpo','O que acontece com o corpo quando você faz yoga regularmente?','Com a prática regular, o corpo passa por mudanças progressivas: melhora da qualidade do sono (semanas 1 a 2), redução dos níveis basais de ansiedade (semanas 2 a 6), aumento de flexibilidade e força muscular (semanas 4 a 12), melhora postural (meses 2 a 4) e, em muitos casos, redução de dores crônicas. O sistema nervoso muda antes do corpo.','O que a maioria das pessoas não espera: as mudanças mais profundas não são visíveis no espelho. São a sensação de acordar menos tensa, a respiração que ficou mais funda sem que você precisasse lembrar de respirar, a capacidade de notar quando está se sobrecarregando antes que o corpo entre em colapso.',false)+
  faqItem('yoga-mal','Yoga pode fazer mal se praticado errado?','Sim. Yoga praticado sem orientação adequada pode causar lesões — especialmente na coluna, joelhos e ombros. Os erros mais comuns são: forçar posturas além do limite atual do corpo, substituir a respiração pelo esforço muscular e copiar posturas de vídeos sem adaptar ao próprio corpo. A presença de uma professora que vê e corrige em tempo real é a principal proteção contra esses riscos.','A maioria das lesões no yoga não ocorre em posturas avançadas — ocorre em posturas aparentemente simples, feitas com alinhamento incorreto de forma repetida. Por isso, começar com professor ao vivo é uma decisão de segurança, não de conforto.',false)+
  faqItem('yoga-burnout','Yoga para burnout: por onde começar?','Para quem está em burnout, o ponto de entrada é o yoga mais suave disponível: Yoga Restaurativo ou Yoga Nidra. Adicionar intensidade a um sistema nervoso esgotado é contraproducente. O objetivo das primeiras semanas não é "fazer mais" — é ensinar o sistema nervoso que é seguro parar. Isso, por si só, já é o trabalho mais importante.','O paradoxo do burnout é que quem mais precisa descansar é quem mais resiste a descansar. O Yoga Restaurativo funciona exatamente nesse contexto porque não pede esforço — pede rendição. E a rendição, praticada de forma estruturada e segura no tapete, começa a se transferir para a vida fora dele.',false)+
  faqItem('yoga-terapia','Yoga pode ser usado como terapia complementar?','Sim, e crescentemente é prescrito como tal. Organizações como a American Psychological Association e o National Institutes of Health reconhecem o yoga como terapia complementar eficaz para ansiedade, depressão leve a moderada, dor crônica, insônia e TEPT. No Brasil, o Ministério da Saúde incluiu práticas integrativas — entre elas o yoga — no SUS em 2017.','Terapia complementar significa que o yoga age ao lado de tratamentos convencionais, não no lugar deles. O que ele oferece que a terapia falada não oferece é o acesso ao corpo — à tensão que o sistema nervoso carrega de forma não-verbal e que a conversa sozinha raramente alcança.',false)
)+
cat(4, 'Yoga para Mulheres 40+: Menopausa, TPM e Ciclo',
  faqItem('yoga-menopausa','Yoga para menopausa: alivia os calores e outros sintomas?','Sim. Estudos clínicos documentam redução significativa da frequência e intensidade das ondas de calor em mulheres que praticam yoga regularmente — particularmente técnicas de respiração que ativam o sistema nervoso parassimpático. O yoga também demonstra eficácia para os outros sintomas da menopausa: insônia, oscilações de humor, rigidez articular e ansiedade elevada.','O mecanismo não é hormonal — o yoga não repõe estrogênio. Mas atua diretamente nos sistemas que o estrogênio regulava: o sistema nervoso autônomo (que controla a temperatura corporal), o sistema límbico (que processa emoções) e o sistema musculoesquelético. Abordar esses sistemas por fora — via respiração, movimento e atenção — produz alívio real e mensurável.',true)+
  faqItem('yoga-50-anos','É tarde para começar yoga aos 40, 50 ou 60 anos?','Não. O yoga é uma das práticas com menor barreira de entrada para adultos mais velhos. Não há limite de idade para começar, e os benefícios são proporcionalmente maiores para quem começa depois dos 40 — porque é exatamente nessa fase que os principais problemas que o yoga resolve se instalam: insônia, ansiedade, dores articulares, rigidez, esgotamento.','O corpo de uma mulher de 50 anos que nunca praticou yoga não está "atrasado" — está no ponto de partida. E esse ponto de partida tem vantagens que os 20 anos não tinham: consciência corporal acumulada, motivação real em vez de estética. As alunas que mais evoluem são, frequentemente, as que chegam depois dos 45.',false)+
  faqItem('yoga-tpm','Yoga para TPM funciona mesmo?','Sim. Posturas específicas de yoga aliviam cólicas, reduzem a retenção de líquido, estabilizam o humor e diminuem a irritabilidade associada à TPM. O mecanismo inclui estímulo ao sistema linfático, regulação do cortisol e ativação do nervo vago — que contrabalança o estado de hiperativação do sistema nervoso que a queda hormonal pré-menstrual provoca.','A prática durante a fase pré-menstrual deve ser mais suave do que o habitual: posturas restaurativas, flexões para frente suaves e respirações longas funcionam melhor do que fluxos dinâmicos. Durante a menstruação, a maioria das professoras recomenda evitar inversões intensas — mas manter a prática suave é benéfico, não contraindicado.',false)+
  faqItem('yoga-hormonal','O que é yoga hormonal e para quem é indicado?','Yoga hormonal é uma prática desenvolvida pela terapeuta brasileira Dinah Rodrigues que combina posturas de yoga, respiração e técnicas de energização com o objetivo de estimular o sistema endócrino feminino. É indicado principalmente para mulheres na perimenopausa e menopausa que buscam aliviar sintomas hormonais de forma complementar.','Diferente do yoga convencional, o yoga hormonal tem uma sequência específica e não substituível — as posturas foram escolhidas por seu efeito sobre glândulas específicas. Por isso, é uma das modalidades em que a qualificação da professora é especialmente crítica.',false)+
  faqItem('yoga-menstruacao','Posso fazer yoga durante a menstruação?','Sim, com adaptações. A prática de yoga durante a menstruação é segura e pode aliviar desconforto — mas deve ser mais suave do que o habitual. A maioria das tradições de yoga recomenda evitar inversões intensas durante o fluxo mais intenso. Posturas restaurativas, flexões suaves para frente e respiração abdominal são especialmente benéficas.','O corpo durante a menstruação está em fase de descida e renovação — não de ascensão e esforço. Adaptar a prática a esse ritmo não é fraqueza, é inteligência corporal. Uma boa professora oferece variações para esse período sem que você precise pedir.',false)+
  faqItem('yoga-menopausa-peso','Yoga pode ajudar com ganho de peso da menopausa?','O yoga contribui para o controle do peso na menopausa por três caminhos: reduz o cortisol cronicamente elevado (que favorece o acúmulo de gordura abdominal), melhora a qualidade do sono (que regula os hormônios da fome) e desenvolve consciência corporal que tende a se transferir para escolhas alimentares mais cuidadosas. Não é uma solução isolada, mas é um componente relevante.','A redistribuição de gordura que ocorre na menopausa está diretamente relacionada ao aumento do cortisol e à piora do sono. O yoga endereça ambos simultaneamente. Combinado com acompanhamento nutricional adequado, a prática regular produz diferença mensurável na composição corporal ao longo de 3 a 6 meses.',false)
)+
cat(5, 'Modalidades: Guia Comparativo',
  faqItem('melhor-yoga-iniciantes','Qual tipo de yoga é melhor para iniciantes?','Para a maioria dos adultos que começam do zero, Hatha Yoga é o ponto de entrada mais recomendado: ritmo pausado, posturas mantidas por algumas respirações, espaço para aprender o alinhamento com segurança. Yoga Restaurativo é a segunda opção, especialmente para quem está esgotada ou com dor crônica. Vinyasa é mais adequado para quem já tem alguma base ou vem de prática física regular.','A escolha ideal depende do objetivo. Para quem quer aprender o básico sem pressa: Hatha. Para quem precisa de um reset do sistema nervoso: Restaurativo ou Yoga Nidra. Para quem se sente agitada demais para "ficar parada": Vinyasa, que ocupa a mente com o movimento. Para quem tem rigidez articular crônica: Yin Yoga, que trabalha o tecido conjuntivo profundo.',true)+
  faqItem('yoga-nidra','O que é yoga nidra e como fazer?','Yoga Nidra é uma prática de relaxamento guiado feita completamente deitada. O praticante é conduzido por voz através de camadas progressivas de consciência corporal, chegando a um estado entre vigília e sono onde o sistema nervoso se restaura profundamente. Uma sessão de 30 minutos é frequentemente descrita como equivalente a 2 a 3 horas de sono em termos de recuperação do sistema nervoso.','Para fazer: deite-se em posição confortável, feche os olhos e siga a voz da professora. Não é necessário "conseguir não pensar" — pensamentos vêm e vão normalmente. O que muda é a relação com eles: você observa sem seguir. Isso é yoga nidra em prática.',false)+
  faqItem('yin-yoga','O que é yin yoga e como é diferente dos outros estilos?','Yin Yoga é uma prática lenta onde cada postura é mantida por 3 a 10 minutos com o corpo relaxado. O alvo não são os músculos — são os tecidos conjuntivos profundos: fáscia, ligamentos e cápsulas articulares. É o único estilo de yoga que trabalha diretamente esse tecido, que não responde ao esforço muscular mas cede sob pressão suave e duradoura.','A diferença principal em relação ao Hatha e ao Vinyasa: nesses estilos, você ativa os músculos e trabalha contra a gravidade. No Yin, você relaxa completamente e usa a gravidade a seu favor. Para quem tem rigidez articular crônica ou mobilidade reduzida, o Yin Yoga frequentemente produz mais resultado do que qualquer outro estilo.',false)+
  faqItem('neuroyoga','O que é neuroyoga e para quem é indicado?','Neuroyoga é uma abordagem emergente que integra conhecimentos de neurociência à prática do yoga. Em vez de descrever os efeitos apenas pela tradição, o neuroyoga explica o mecanismo — como o cérebro responde ao movimento, à respiração e à atenção — e usa esse mapa para conduzir práticas mais precisas. É indicado especialmente para quem tem ansiedade, burnout ou dificuldade de conexão com práticas mais tradicionais.','O que distingue o neuroyoga é o vocabulário: em vez de "abra o coração para a gratidão", o professor diz "mantenha essa postura mais três respirações porque a tolerância ao desconforto se aprende exatamente assim". O efeito no corpo é idêntico — a via de entrada é diferente.',false)+
  faqItem('hatha-vs-vinyasa','Qual a diferença entre Hatha e Vinyasa?','Hatha Yoga é pausado — cada postura é mantida por algumas respirações antes de mudar. Vinyasa é fluido — os movimentos fluem sincronizados com a respiração, criando uma sequência contínua. Hatha ensina o alinhamento e a permanência; Vinyasa ensina a fluidez e a presença no movimento. Para iniciantes, Hatha é geralmente mais seguro porque permite mais tempo de aprendizado em cada postura.','A escolha entre os dois é também uma questão de temperamento. Quem funciona melhor com estrutura e pausa tende a gostar mais do Hatha. Quem precisa de movimento para entrar em quietude geralmente encontra no Vinyasa a porta de entrada perfeita. Muitos praticantes acabam combinando os dois ao longo da semana.',false)
)+
cat(6, 'Yoga vs. Outras Práticas',
  faqItem('yoga-vs-pilates','Qual a diferença entre yoga e pilates?','Yoga e pilates trabalham o corpo de formas complementares mas com ênfases distintas. O pilates foca no fortalecimento do core e na estabilidade postural — é predominantemente físico. O yoga integra respiração, atenção mental e regulação do sistema nervoso além do corpo físico. Pilates é mais indicado para reabilitação e força; yoga, para regulação mental e mobilidade.','Ambas as práticas são benéficas e frequentemente se complementam. Quem faz pilates regularmente costuma encontrar no yoga o trabalho de regulação mental e mobilidade que o pilates não oferece. Quem faz yoga frequentemente descobre no pilates um trabalho de fortalecimento muscular mais direcionado.',true)+
  faqItem('yoga-musculacao','Yoga pode substituir a musculação?','Depende do objetivo. Para desenvolvimento de força máxima e hipertrofia muscular intensa, não. Para manutenção de força funcional, controle de peso, saúde articular e equilíbrio muscular, o yoga pode ser suficiente — especialmente modalidades mais ativas como Vinyasa e Yoga HIIT. Para a maioria das pessoas, yoga e musculação se complementam melhor do que se substituem.','O yoga desenvolve o que os praticantes chamam de "força funcional" — a capacidade de sustentar o próprio peso em múltiplas direções, com equilíbrio e controle. Quem combina yoga com musculação frequentemente percebe melhora no desempenho em ambas as práticas.',false)+
  faqItem('yoga-musculacao-mesmo-dia','Posso fazer yoga e musculação no mesmo dia?','Sim, com planejamento. A recomendação geral é: yoga antes da musculação (como aquecimento e ativação) ou yoga algumas horas depois (como recuperação). Evitar yoga intenso imediatamente após musculação pesada, porque o tecido muscular fatigado não responde bem a alongamento forçado. Yoga Restaurativo ou Yoga Nidra após musculação, porém, acelera a recuperação.','Para quem treina musculação de manhã e quer fazer yoga à noite: funciona muito bem. O yoga noturno ajuda a remover o estado de tensão muscular e mental que o treino intenso deixa, melhora a qualidade do sono e prepara o corpo para o próximo treino.',false)+
  faqItem('yoga-cardio','Yoga é considerado cardio?','Depende da modalidade. Vinyasa e Yoga HIIT elevam a frequência cardíaca a zonas de exercício moderado (55 a 70% da frequência máxima) — equivalente a uma caminhada acelerada. Hatha e Restaurativo têm baixo componente cardiovascular. Para os benefícios específicos do exercício aeróbico intenso, o yoga convencional não substitui a corrida ou o ciclismo — mas complementa com o que esses exercícios não oferecem.','O valor cardíaco do yoga vai além da frequência cardíaca durante a sessão. A redução crônica do cortisol, a melhora da variabilidade da frequência cardíaca e a regulação da pressão arterial produzidas pela prática regular são benefícios cardiovasculares que nenhuma métrica de "calorias queimadas por hora" captura.',false)
)+
cat(7, 'Yoga e Religião',
  faqItem('yoga-religiao','Yoga é religião?','Não. Yoga tem origens filosóficas nas tradições indianas, mas praticar yoga não exige nenhuma crença religiosa, filiação espiritual ou mudança de cosmovisão. Os benefícios físicos e mentais — redução de ansiedade, melhora do sono, alívio de dores — estão disponíveis para qualquer pessoa, independentemente do que acredita. A respiração ativa o nervo vago da mesma forma em ateus e em pessoas de qualquer fé.','A confusão entre yoga e religião tem duas origens: a histórica (yoga nasceu dentro de uma tradição filosófica indiana) e a mercadológica (parte da indústria do bem-estar ocidental adotou uma estética "espiritual"). Numa aula de yoga laica, o que acontece é simplesmente movimento, respiração e atenção ao corpo.',true)+
  faqItem('cristaos-yoga','Cristãos podem praticar yoga?','Do ponto de vista da prática laica, sim. Uma aula de yoga que se restringe ao trabalho físico, à respiração e à regulação do sistema nervoso não entra em conflito com nenhum princípio cristão. A questão relevante é o conteúdo da aula: posturas e respiração não têm afiliação religiosa; mantras, invocações e rituais espirituais específicos podem ser incompatíveis com algumas tradições.','A decisão é pessoal e depende da tradição cristã específica de cada pessoa. Consultar sua liderança religiosa é o caminho mais honesto do que buscar uma resposta universal.',false)+
  faqItem('yoga-secular','O que é yoga secular?','Yoga secular é a prática de yoga focada exclusivamente em seus benefícios físicos e mentais, sem qualquer componente espiritual, filosófico ou ritual. Não há mantras, não há referências a divindades, não há afirmações de fé. O vocabulário é de neurofisiologia e anatomia, não de tradição. É o formato mais adequado para pessoas que querem os benefícios do yoga sem o pacote espiritual.','A distinção é importante porque o yoga secular produz os mesmos benefícios documentados que qualquer outra forma de yoga: a respiração consciente ativa o nervo vago independentemente de qualquer cosmologia.',false)
)+
cat(8, 'Yoga Online ao Vivo: Como Funciona',
  faqItem('yoga-online-vs-presencial','Yoga online ao vivo funciona tanto quanto o presencial?','Para a maioria das pessoas, sim — desde que seja ao vivo com professor que vê os alunos, não aula gravada. A diferença fundamental entre yoga online ao vivo e presencial é apenas o toque físico do professor. A correção verbal e visual, a presença, a adaptação em tempo real e a relação com a professora se mantêm integralmente online.','O que muda positivamente no online: a eliminação do deslocamento (que para quatro aulas semanais representa horas recuperadas por mês), a possibilidade de praticar em casa no próprio espaço e a eliminação de barreiras logísticas que interrompem a consistência.',true)+
  faqItem('material-yoga-online','O que preciso para fazer yoga online ao vivo?','Para participar de uma aula de yoga online ao vivo você precisa: tapete de yoga, espaço de aproximadamente 2m x 1m, roupa confortável, conexão à internet estável e câmera funcionando. A câmera ligada é importante: é através dela que a professora faz as correções de postura em tempo real. Sem câmera, a aula se torna equivalente a um vídeo gravado.','O espaço ideal tem boa iluminação e posição da câmera que permita à professora ver o corpo inteiro. Muitas alunas usam o computador sobre uma superfície elevada ou posicionam o celular lateralmente para capturar o corpo de comprido.',false)+
  faqItem('correcao-postura-online','A professora consegue corrigir minha postura em uma aula online?','Sim, com precisão surpreendente. A correção verbal guiada visualmente — "afaste o joelho direito 2 centímetros, sinta o peso distribuir no calcanhar" — é tão eficaz quanto o ajuste manual para a maioria das posturas. A professora vê o alinhamento, identifica as compensações e guia a correção em tempo real.','A única correção que o formato online não oferece é o toque físico — o ajuste manual de um ombro, o reposicionamento de um quadril com as mãos. Para a maioria das alunas e da maioria das posturas, essa limitação é marginal.',false)+
  faqItem('escolher-professora-yoga','Como escolher uma professora de yoga online?','Os critérios mais importantes: formação certificada por escola reconhecida (mínimo 200 horas), experiência de ensino comprovada, especialização na modalidade que você busca e — principalmente — a sensação de estar à vontade na presença dela. Nenhum certificado substitui a experiência de fazer uma aula experimental e verificar se o estilo de ensino faz sentido para você.','Avalie também: a professora vê os alunos durante a aula? Adapta as posturas para diferentes corpos e limitações? Oferece suporte fora das aulas? A primeira aula experimental não é só para conhecer o yoga — é para conhecer a professora.',false)+
  faqItem('plataforma-yoga-online','Qual aplicativo ou plataforma usar para aulas de yoga online ao vivo?','A plataforma mais usada para aulas de yoga online ao vivo no Brasil é o Zoom. A experiência com o Zoom é superior a outras plataformas para esse formato porque oferece boa qualidade de vídeo e áudio, permite à professora ver todos os alunos simultaneamente e tem estabilidade comprovada para sessões de 60 a 90 minutos.','Para alunas iniciantes no formato online: antes da primeira aula, teste a câmera e o microfone, verifique a velocidade da internet e configure o espaço de prática. Não é tecnicamente complexo — e a maioria das dificuldades técnicas se resolve na primeira semana.',false)+
  faqItem('ao-vivo-vs-gravado','Aulas ao vivo são melhores do que vídeos gravados de yoga?','Para aprendizado e segurança, sim — especialmente para iniciantes. Vídeos gravados são úteis para complementar a prática, revisar posturas ou praticar quando não há aula ao vivo disponível. Mas não substituem a presença de um professor que vê você: sem correção em tempo real, é fácil desenvolver hábitos posturais incorretos sem perceber. A aula ao vivo é proteção — não luxo.','A dimensão relacional também é irreplicável em vídeo: a professora sabe seu nome, percebe quando você faltou, nota quando algo mudou no seu corpo ou no seu humor. Essa presença — saber que alguém te vê e te espera — é um dos fatores mais subestimados na construção de um hábito consistente de prática.',false)
)+
cat(9, 'Perguntas "Posso": Situações Específicas',
  faqItem('yoga-gravidez','Posso fazer yoga na gravidez?','Sim, com acompanhamento qualificado. Yoga na gravidez é seguro e benéfico para a maioria das mulheres — reduz dores lombares, alivia edema, melhora a qualidade do sono e prepara o corpo e a respiração para o parto. A condição essencial é informar à professora sobre a gravidez, semana gestacional e qualquer restrição médica, e praticar exclusivamente sob orientação de professora com formação específica em yoga para gestantes.','As restrições variam por trimestre: no primeiro, evitar posições de bruços e inversões intensas; no segundo e terceiro, adaptar posturas em decúbito dorsal para evitar compressão da veia cava. Uma professora com formação específica conhece essas adaptações.',true)+
  faqItem('yoga-lombar','Posso fazer yoga com dor na lombar?','Depende da origem e intensidade da dor. Para dor lombar crônica sem diagnóstico de hérnia discal aguda ou instabilidade vertebral: yoga é frequentemente recomendado como parte do tratamento — fortalece o core, melhora a mobilidade dos quadris e corrige padrões posturais que sobrecarregam a lombar. Para dor aguda ou com diagnóstico específico: consultar o médico antes de começar.','A informação mais importante: diga à professora sobre a dor antes da aula. Uma professora qualificada saberá quais posturas adaptar, quais evitar e como trabalhar de forma que a prática seja terapêutica em vez de agravar.',false)+
  faqItem('yoga-antes-dormir','Posso fazer yoga antes de dormir?','Sim — e é uma das aplicações mais eficazes do yoga. Uma prática de 20 a 45 minutos entre 1 e 2 horas antes de dormir, focada em posturas suaves, respiração longa e finalizada com Savasana ou Yoga Nidra, produz redução mensurável nos níveis de cortisol e prepara o sistema nervoso para o sono. Evitar Vinyasa intenso ou Yoga HIIT próximo ao horário de dormir.','Para quem tem dificuldade de "desligar" antes de dormir, o yoga noturno funciona como uma transição ritualizada entre o dia e a noite. O corpo aprende, com a repetição, que essa sequência de movimentos e respiração sinaliza que o dia terminou.',false)+
  faqItem('yoga-depois-comer','Posso fazer yoga depois de comer?','O ideal é aguardar pelo menos 2 horas após uma refeição grande e 1 hora após uma refeição leve antes de praticar yoga. Posturas de torção, inversões e flexões abdominais são desconfortáveis e potencialmente prejudiciais com o estômago cheio. Yoga Nidra e meditação são exceções — podem ser feitos com menos intervalo porque não envolvem compressão abdominal.','A recomendação não é por superstição: é anatomia. O diafragma tem mobilidade reduzida quando o estômago está cheio. As torções e compressões abdominais que o yoga inclui podem causar náusea ou refluxo quando feitas com digestão em andamento.',false)+
  faqItem('yoga-cadeira','Posso fazer yoga na cadeira?','Sim. Yoga na cadeira — também chamado de Chair Yoga — é uma modalidade adaptada para pessoas com mobilidade reduzida, condições ortopédicas que limitam posturas no chão, ou que passam muito tempo sentadas. Mantém os benefícios essenciais do yoga: respiração consciente, mobilidade articular, atenção ao corpo e regulação do sistema nervoso.','É especialmente indicado para quem trabalha muitas horas sentada, para idosos com dificuldade de se sentar no chão, e como alternativa para dias em que o corpo não permite a prática completa. Muitas posturas de yoga têm versões igualmente eficazes realizadas na cadeira.',false)+
  faqItem('yoga-gripada','Posso fazer yoga gripada ou resfriada?','Depende da intensidade dos sintomas. Sintomas leves — leve congestão, cansaço moderado — admitem uma prática suave: Hatha devagar, Yoga Restaurativo ou Yoga Nidra. Febre, sintomas intensos ou gripe declarada pedem repouso total. O sistema imune em resposta ativa precisa de energia — qualquer prática física a desvia para o músculo em vez de para a defesa.','Há posturas que podem auxiliar na recuperação de resfriados leves — especialmente inversões suaves como "pernas na parede" e práticas de respiração que facilitam a drenagem nasal. Mas o julgamento deve ser honesto: se o corpo está pedindo descanso, é repouso — não o tapete.',false)
)+
cat(10, 'Resultados: O Que Esperar',
  faqItem('yoga-emagrece','Yoga emagrece?','Yoga contribui para o controle de peso, mas não é primariamente uma prática de emagrecimento. O mecanismo não é principalmente o gasto calórico: é a regulação do cortisol cronicamente elevado — que está diretamente associado ao acúmulo de gordura abdominal — e a melhora da qualidade do sono, que regula os hormônios da fome. A consciência corporal que o yoga desenvolve também tende a influenciar escolhas alimentares.','Para quem pratica yoga com regularidade: a maioria não relata perda de peso expressiva nas primeiras semanas, mas relata mudança na relação com o próprio corpo — e com a comida. Isso se traduz, ao longo de meses, em hábitos que sustentam um peso mais saudável de forma muito mais duradoura do que qualquer dieta de curto prazo.',true)+
  faqItem('yoga-define-corpo','Yoga define o corpo?','Sim, com prática regular e consistente. Modalidades ativas de yoga — Vinyasa, Hatha intenso, Yoga HIIT — desenvolvem força muscular funcional, melhoram o tônus e a postura. O resultado visual é um corpo mais alongado, mais sustentado e com melhor alinhamento. Não é o mesmo resultado da musculação com cargas — é uma definição diferente: mais funcional, mais integrada.','O que mais transforma a aparência no yoga não é o músculo isolado — é a postura. Uma coluna mais ereta, ombros naturalmente afastados das orelhas e quadril bem alinhado mudam silhueta e presença de forma que nenhum exercício de foco muscular isolado consegue.',false)+
  faqItem('tempo-resultado-yoga-2','Em quanto tempo o yoga produz resultados perceptíveis?','Os primeiros resultados são rápidos: melhora do sono e redução de ansiedade costumam aparecer nas primeiras duas semanas de prática consistente. Flexibilidade e redução de dores crônicas aparecem entre 4 e 8 semanas. Mudanças de força, postura e composição corporal levam de 3 a 6 meses. A ordem importa: o sistema nervoso muda antes do corpo.','A variável mais determinante não é a intensidade da prática — é a consistência. Três sessões por semana durante três meses produzem resultados incomparavelmente maiores do que sessões diárias durante três semanas. O corpo responde a padrões repetidos, não a esforços concentrados.',false)+
  faqItem('yoga-postura','Yoga melhora a postura?','Sim — e é uma das mudanças mais universalmente relatadas por praticantes regulares. O yoga fortalece a musculatura profunda da coluna e do core, aumenta a consciência do próprio corpo no espaço e libera as tensões musculares crônicas que tracionam a coluna para fora do eixo. Mudanças posturais perceptíveis costumam aparecer entre 6 e 12 semanas de prática regular.','A melhora postural no yoga não vem de "tentar ficar ereta" com esforço — vem de fortalecer o que sustenta a postura sem esforço. Quando o core funciona corretamente, a coluna se alinha naturalmente. Quando os ombros liberam a tensão crônica, eles caem no lugar certo sem que você precise lembrá-los.',false)+
  faqItem('yoga-contraindicacoes','O yoga tem contraindicações?','Yoga tem poucas contraindicações absolutas, mas exige adaptações em algumas condições. Requerem atenção especial: glaucoma (inversões contraindicadas), hérnia discal aguda, gravidez de alto risco, hipertensão descontrolada e cirurgias recentes. Para todas essas condições, informe a professora antes da primeira aula.','A regra geral: se você tem uma condição médica diagnosticada, informe a professora antes de começar. Uma professora qualificada conhece as adaptações necessárias e pode conduzir a prática de forma segura — ou indicar quando o clearance médico é necessário antes de iniciar.',false)
)+
`
  </div>
</section>`;

let html = fs.readFileSync(path, 'utf8');
html = html.replace('<!-- FAQ_PLACEHOLDER -->', faqHtml);
fs.writeFileSync(path, html, 'utf8');
console.log('FAQ done, size:', fs.statSync(path).size);
